### ISSUE TITLE
Issuing Git commands

### ISSUE THREAD

**Issue by LindsayTafone** [jafish/File-Management-and-Version-Control#14]
I suppose my notes are incomplete, but what are the steps for, well, starting Git? 

Opening the Git CMD tool, I can't submit any of the phases we learned, I assume because I'm in command line within Git CMD and somehow not running Git in Git CMD? My errors are such that "'pwd' (or 'ls / clear') is not recognized as an internal or external command, operable program, or batch file". I can navigate with cd to where my repository is, and I thought maybe it would recognize my commands in there, but no dice.

Related, but when I want to be using "git add," should I be navigated to the file itself, or the folder containing the .txt file? This question might have answered itself if I could view "ls," but...

Thanks guys!

**Comment by jafish** [comment]
You might be in the wrong tool for the commands that we covered last week, which were mostly shell commands. Are you able to run them in Git Bash instead of Git CMD?
