### ISSUE TITLE
How do I PERMANENTLY delete a part of my code? how does .gitignore work?

### ISSUE THREAD

**Issue by kerrinrose** [jafish/File-Management-and-Version-Control#15]
So that it doesn't appear in any of my previous commits? For example, if I accidentally commit code with sensitive information like an API key or password, and then I attempt to remove this information, it will still be visible in my previous commits and someone could find the info. How does .gitignore work to prevent this? Also, if you have a private repo, is it safe to include this sensitive info or is that not a good practice?

**Comment by domportera** [comment]
I'm pretty sure .gitignore simply ignores local files so they own't be uploaded to Git. I'm not sure you can get rid of that if you want to keep your file in the repo. I think making the repo private would be just fine. Not that this is coming from any place of expertise.

**Comment by LindsayTafone** [comment]
I don't quite know, but you might find a solution in git reset --hard (nuclear option, apparently, with git revert commitid being for adding a negative change, if I'm reading [this link](http://41j.com/blog/2015/02/common-git-screwupsquestions-solutions/) correctly)

**Comment by kbohinski** [comment]
Lots of info here
https://rtyley.github.io/bfg-repo-cleaner/

**Comment by kbohinski** [comment]
Its ok\* to have in a private repo, although you shouldn't in case it goes public at some point or your keys/account are compromised.

The recommended way is to use something like this https://www.agwa.name/projects/git-crypt/

**Comment by kbohinski** [comment]
.gitignore only works from 'now on'. It does nothing retroactively.

Hope this helps.

**Comment by jafish** [comment]
@kerrinrose I would keep sensitive information like usernames/passwords/private keys far away from text files in a repository, unless they really need to be there for some reason. Like @kbohinski's link suggests, some sort of encryption is really the best way to store that info. Something like [KeePass](http://keepass.info) or [1Password](https://1password.com). But if you just need to edit a commit message before pushing to a remote, you can use `git commit --amend`

**Comment by jafish** [comment]
Actually just stumbled upon an article that answers @kerrinrose's exact question: https://help.github.com/articles/remove-sensitive-data/
