### ISSUE TITLE
Timeout Question

### ISSUE THREAD

**Issue by LindsayTafone** [jafish/File-Management-and-Version-Control#17]
If using this command from [here](http://41j.com/blog/2015/02/common-git-screwupsquestions-solutions/)
git config --global credential.helper "cache --timeout=XXXX"
What would be the point of saving a cache with my password on it, if I have a key system set up?

**Comment by jafish** [comment]
The article mentions that this command is for https connections, but if you have SSH key authentication set up then git will use that instead (so there would be no point in this command).
