### ISSUE TITLE
Question on Project

### ISSUE THREAD

**Issue by jessmcguire** [jafish/File-Management-and-Version-Control#26]
Hello,

My question is regarding our project. I have a large paper that I have been working on for the entire semester and would like to use that for the project. Being that I'm not at all familiar with GitHub I didn't know if a paper would be an acceptable project to use. Also given that I'm near the end of the semester my paper is nearly done. Are small changes ok for this assignment?

**Comment by jafish** [comment]
**_Finally_** answered this question.
